### ISSUE TITLE
Add wordlists (or relate)

### ISSUE THREAD

**Issue by CodeBrauer** [balzss/cli-typer#5]
I just saw there wasn't anything similar on :octocat: so I created a repo for this:
https://github.com/CodeBrauer/1000-most-common-words

Maybe this could be somehow added with rawgit.com or you can just put a small link it your readme

**Comment by CodeBrauer** [comment]
> I checked the Hungarian wordlist and it seems to contain many non-word, multiple words on a line and e.g. "Bell" is not even a Hungarian word.

I tried to find any other source than 1000mostcommonwords.com, but didn't found anything similar. Maybe this repo needs some collaborative refactoring

**Comment by balzss** [comment]
Closing this as it is not related to this repository.
